PREFIX alternativedesignsofmountingbracket:<http://opencaesar.io/template/vocabulary/authtool/disciplinevocabularies/alternativedesignsofmountingbracket#>
SELECT ?x ?y
WHERE {
  ?x alternativedesignsofmountingbracket:boundaryConditions ?y .
}